初步完成ADT
HIT-ReFreSH/OpenSchedule pull request #2
Opened 2020-11-02 12:57 UTC by cccccent

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Sorry, No Test

**Test Configuration**:
* Operating System:
* Hardware:
* SDK Version:

# Checklist:

- [1] My code follows the style guidelines of this project
- [1] I have performed a self-review of my own code
- [1] I have commented my code, particularly in hard-to-understand areas
- [1] I have made corresponding changes to the documentation
- [1] My changes generate no new warnings
- [0] I have added tests that prove my fix is effective or that my feature works
- [1] New and existing unit tests pass locally with my changes
- [1] Any dependent changes have been merged and published in downstream modules

2020-11-02 12:59 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        public Course(string name, string IdNum)
IdNum是什么？
- 不符合形式参数命名规范
- 没有XML注释

2020-11-02 13:07 UTC, cccccent commented on OpenSchedule/Course.cs
> +        public Course(string name, string IdNum)
指这一个变量不满足下面两点，还是全部变量？

2020-11-02 13:14 UTC, mahoshojoHCG requested changes
问题很大，请逐条修改

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        /// <param name="name">the name of the course</param>
the name of the course表意不清，请考虑 Name of the course.

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +﻿using System.Collections.Generic;
头部没有添加Apache协议文本，所有源代码都有这个问题。

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        public string GetCourseName()
这是什么？

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        ///     get the name of the course
英文请使用大写开头

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        ///     一门课程，实际为若干课程信息和考试信息的集合
请不要中英文混搭，不同语言请写入单独的XML

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        private string CourseId { get; }
没有XML注释

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        ///     一门课程，实际为若干课程信息和考试信息的集合
而且注释门不对题

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        public string GetCourseName()
请使用属性

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        ///     get the Id of the Course
请修改注释内容

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        public string GetCourseId()
请使用属性

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        ///     add a new course event to the course
请修改注释以匹配英文语法，下同，以后不再提醒

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/CourseInformation.cs
> +﻿using System;
头部没有添加Apache协议文本，所有源代码都有这个问题。

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/CourseInformation.cs
> +        ///     继承自类EventInformation，表示一个课程。内容包括：教师名称 Teacher，以及父类的变量Classroom, StartTime, Duration
语言问题

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +﻿using System;
头部没有添加Apache协议文本，所有源代码都有这个问题。

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +        ///     the constructor of class EventInformation
the constructor

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +        ///     a new constructor of class EventInformation, only used in method clone()
为什么这里又用a了，请仔细检查英文语法

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +        public EventInformation(string room, DateTime start, TimeSpan duration, Guid Id)
如果你只打算再Clone()方法中使用，可以考虑使用私有的构造函数，而且只在一处使用的话可以直接写在Clone()方法里

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +        ///     表示一个事件的信息（可以是课程，也可以是考试），内容包含:地点 classroom，开始时间 StartTime，时长 EventDuration
语言问题

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +            return new EventInformation(Classroom, StartTime, EventDuration, EventId);
ICloneable返回的是object，请添加返回实例相同类型的方法，并且将改方法签名修改为ICloneable.Clone()

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +        ///     1 if the obj is null
null请抛出异常

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +        public int CompareTo(object obj)
请同时实现ICompare<T>

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/ExamInformation.cs
> +﻿using System;
头部没有添加Apache协议文本，所有源代码都有这个问题。

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        private readonly ISet<ExamInformation> ExamSet = new SortedSet<ExamInformation>();
私有字段不满足命名规则，正确的应该是_courseSet, _examSet

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        private string CourseId { get; }
Id应使用GUID类型

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Schedule.cs
> +        ///     某个人的课程表，是他所需要上的所有课程的集合。
语言问题

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Schedule.cs
> +        ///     the schedule of a student, containing all the course of the student.
用户不一定是student

2020-11-02 13:14 UTC, mahoshojoHCG commented on OpenSchedule/Schedule.cs
> +        public string GetStudentName()
请使用属性

2020-11-02 13:15 UTC, mahoshojoHCG commented on OpenSchedule/Course.cs
> +        public Course(string name, string IdNum)
只看到了这一点

2020-11-03 08:22 UTC, mahoshojoHCG requested changes

2020-11-03 08:22 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +    public class EventInformation : IComparable, ICloneable
考虑更改为abstract class

2020-11-03 08:27 UTC, mahoshojoHCG requested changes

2020-11-03 08:27 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +            if (obj == null) throw new NullReferenceException();
null判断不需要，如果是null，他也不是EventInformation。

2020-11-03 08:27 UTC, mahoshojoHCG commented on OpenSchedule/EventInformation.cs
> +            throw new ArgumentException("Object is not a EventInformation");
考虑使用name的重载

2020-11-03 08:27 UTC, mahoshojoHCG commented
不要忘记添加单元测试

2020-11-05 06:51 UTC, FerdinandSukhoi commented
已经添加单元测试，并修正了一些不规范的内容

2020-11-05 06:56 UTC, FerdinandSukhoi commented
已经清理代码

2020-11-05 07:21 UTC, mahoshojoHCG approved these changes

2020-11-05 07:22 UTC, merged